# My first cool idea

#### Keywords

Opportunity scoring

## A beginning.

Every one of us fail at times. And then, we look back in retrospect and wonder how things could have gone differently. But if we could start our endeavors with this hindsight, we could avoid many failures.

Sales teams are often surrounded with enormous numbers of opportunities, which makes picking win opportunities very challenging, if not impossible. For many sales teams, they need more rapid and real-time access to actionable insights, intelligent recommendations and collaboration tools that can show them which opportunity to prioritize and which deals may require a bit of extra effort. They want to be focused on the highest value and deals through automated scoring rules informed by predictive analytics. They also want to forecast revenue and bookings numbers based on current opportunities.


## A middle.

Using machine-learning techniques, we can score sales opportunities to determine the likelihood of winning a deal. Sales reps can then use these scores to prioritize the opportunities they work on. 

We can use text-mining techniques to scrape data from email communications between sales representatives and customers to evaluate the success probability of a deal. In addition, we can take the following feature specifications into consideration:

*  Revenue potential, customer historical transactions, resource requirement, familiarity, conflicts, cost of sales, customer    relationships, and responsible sales representatives’ performance
  
Once we have defined all the relevant criteria, definitions and applied the scoring, we can then move to create a matrix or dashboard that helps visualize which opportunities will deliver the greatest value with the lowest amount of risk or cost.

In addition, we can create a predictive model – based on all the historical opportunities and whether they successfully converted into win deals. The model can look at all the attributes of the opportunity including custom fields and identifies which attributes are most correlated to successful conversions. The output is a predictive model with weightings for each attribute. This model can then be applied to every new opportunity to predict whether it will result in a successful conversion.
 


## An end.

Keeping score of the opportunities provides a consistent methodology to measure and prioritize the right opportunities sales teams should be pursuing in their pipeline. Opportunity scoring is a powerful tool to help them separate the winners from the losers with insights in business intelligence and predictive analytics.
