# My second cool idea - AMERHOPE
Connect Chinese students with English teachers

#### Keywords
Remote Learning, Student Matching, Customized Studies

## Greater Demand for Native English-Speaking Teachers in China
Dear investors, 
China’s online English education market is estimated to grow at more than 50 per cent a year to 90 billion USD by 2020[1]. Affluent middle-class families have more demands for qualified native English speakers to teach their children both English and other subjects in English. However, with limited resources, the student to foreign teacher ratio is only 40 to 1 in urban areas. It is even harder for students in rural areas to receive qualified education. On the other side, more teachers are exploring ways to benefit through cross-cultural and personal enrichment.  AMERHOPE's vision is to provide a platform to connect English teachers in America, UK, Australia, and Canada with students in China. Internet-enabled artificial intelligence can help provide more tailor-made curricula after online assessment. 


## What AMERHOPE Can Do
AMERHOPE can provide online education platform that offers an American elementary education experience to Chinese students. We will hire qualified teachers with experience in the North American classroom to give one-on-one, fully immersive lessons delivered via our platform and based on U.S. Standards. The process will adhere to a flipped classroom model, entailing a pre-class video that introduce key learning points, interactive one-on-one instruction that reinforce learning objectives, and follow-up, post class homework.

As we attract more students and teachers, data science can help us match students with teachers based on their learning or teaching pattern. For example, some students like patient teachers while others tend to study better with encouraging ones. Likewise, some teachers enjoy working with smart and creative students while others tend to get along with obedient ones. We will apply machine learning to study both students' and teachers' behaviors to provide a more tailored curricula. 


## Don't Miss This Opportunity
Our service is tapping into the demand among Chinese middle-class parents to have their children learn English in the most authentic way and the desire of underpaid English teachers to make more money during their spare time. Do not miss this opportunity to help the younger generation build a better future!

## Reference: 
Chen, Lydia. 2016. "Golden Age of China's Education Industry". Technology, Media & Telecommunications Industry, Deloitte China. https://www2.deloitte.com/content/dam/Deloitte/cn/Documents/technology-media-telecommunications/deloitte-cn-tmt-golden-age-of-the-chinese-education-market-en-160713.pdf 
