---
title: "W201 Portfolio"
author: "Yuqing Grace Lin"
date: "MIDS Fall 2017"
site: bookdown::bookdown_site
documentclass: book
---

# Welcome!

This site contains the data-related ideas of Grace Lin, a student of the MIDS program at University of California, Berkeley. These are a couple of ideas I would like to explore. 

<!-- Below this line is just examples of how you can embed video from Google Drive. First you have to enable sharing, then just get the object ID which is that long string between d/ and /preview and will also be appended to any sharing link you generate for your video. -->
<p>
```{r hello,echo=FALSE,fig.cap='Opportunity Scoring!',fig.align='center'}
knitr::include_url("https://drive.google.com/file/d/14Q75yHXMoo14Qup5fdgHgNdhLzVXv2fV/preview")
```

### Abstract of my first cool idea

Sales teams are often surrounded with an enormous number of opportunities, which makes picking winning opportunities very challenging, if not impossible. Many sales teams lack rapid and real-time access to actionable insights, intelligent recommendations and collaboration tools that can show them which opportunities to prioritize and which deals may require a bit of extra effort. Using predictive analytics, our team can create automated scoring rules to prioritize the highest value deals. In addition, this will let salespeople forecast revenue and bookings numbers based on opportunities currently in their pipeline. 

Scoring the opportunities provides a consistent methodology to prioritize the right opportunities sales teams should be pursuing in their pipeline. Opportunity scoring is a powerful tool to help them separate the winners from the losers with insights from business intelligence and predictive analytics.

### Abstract of my second cool idea

China’s online English education market is estimated to grow at more than 50 per cent a year to 90 billion USD by 2020. AMERHOPE can provide online education platform that offers an American elementary education experience to Chinese students. We will hire qualified teachers with experience in the North American classroom to give one-on-one, fully immersive lessons delivered via our platform and based on U.S. Standards. The process will adhere to a flipped classroom model, entailing a pre-class video that introduce key learning points, interactive one-on-one instruction that reinforce learning objectives, and follow-up, post class homework. 

As we attract more students and teachers, data science can help us match students with teachers based on their learning or teaching pattern. For example, some students like patient teachers while others tend to study better with encouraging ones. Likewise, some teachers enjoy working with smart and creative students while others tend to get along with obedient ones. We will apply machine learning to study both students' and teachers' behaviors to provide a more tailored curricula.
  
### About the Author
Grace is an analyst at TIBCO Software Inc in Palo Alto, California. She is currently pursing a Master of Science in Information and Data Science degree at UC Berkeley.

At TIBCO, she generated more than $80M cash liquidity worldwide. She used maching-learning techniques and automated a foreign exchange (FX) real-time exposure and hedging strategy system using Python and TIBCO Spotfire, a data visualization tool. 

In her free time, she loves adventures aroud the world. 


*Updated: `r Sys.Date()`*
